"""Descripción de la migración

Revision ID: 031d48d7a74e
Revises: 
Create Date: 2023-08-11 20:08:48.972209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031d48d7a74e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ingresos', sa.Column('concepto', sa.String(), nullable=True))
    op.add_column('Ingresos', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('Ingresos', sa.Column('periodicidad', sa.String(), nullable=True))
    op.add_column('Ingresos', sa.Column('fechaingreso', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ingresos', 'fechaingreso')
    op.drop_column('Ingresos', 'periodicidad')
    op.drop_column('Ingresos', 'descripcion')
    op.drop_column('Ingresos', 'concepto')
    # ### end Alembic commands ###
