"""Añadir tablas Ingresos y Gastos

Revision ID: 06aa56a2870e
Revises: 788ad5cb2467
Create Date: 2023-08-11 22:05:53.129567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06aa56a2870e'
down_revision: Union[str, None] = '788ad5cb2467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('idingresos', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('periodicidad', sa.String(), nullable=True),
    sa.Column('fechaingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.cedula'], ),
    sa.PrimaryKeyConstraint('idingresos')
    )
    op.drop_table('Ingresos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingresos',
    sa.Column('idingresos', sa.INTEGER(), nullable=False),
    sa.Column('idusuario', sa.INTEGER(), nullable=True),
    sa.Column('concepto', sa.VARCHAR(), nullable=True),
    sa.Column('monto', sa.FLOAT(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('periodicidad', sa.VARCHAR(), nullable=True),
    sa.Column('fechaingreso', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.cedula'], ),
    sa.PrimaryKeyConstraint('idingresos')
    )
    op.drop_table('ingresos')
    # ### end Alembic commands ###
