"""Modificando el database

Revision ID: 788ad5cb2467
Revises: 031d48d7a74e
Create Date: 2023-08-11 21:50:30.990041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788ad5cb2467'
down_revision: Union[str, None] = '031d48d7a74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.drop_table('ingresos')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('idingresos', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('periodicidad', sa.String(), nullable=True),
    sa.Column('fechaingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.cedula'], ),
    sa.PrimaryKeyConstraint('idingresos')
    )
    op.drop_table('Ingresos')
    # ### end Alembic commands ###
    

    # ### end Alembic commands ###
